version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket passmapi-server --output-template-file passmapi-packaged-template.yml
artifacts:
  files:
    - passmapi-packaged-template.yml