version: 0.2
phases:
  install:
    runtime-versions:
        python: 3.8
  build:
    commands:
      - sam package --template-file template.yaml --s3-bucket passmapi-api --output-template-file passmapi-packaged-template.yml --image-repository ["HelloWorldFunction=541382795025.dkr.ecr.us-west-1.amazonaws.com/helloworldfunction", "GetPasswords=541382795025.dkr.ecr.us-west-1.amazonaws.com/getpasssword"]

artifacts:
  files:
    - passmapi-packaged-template.yml